modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/MajruszLibrary/issues"

[[mods]]
    modId="majrusz_library"
    version="2.6.0"
    displayName="Majrusz Library"
    updateJSONURL="https://raw.githubusercontent.com/Majrusz/MajruszLibrary/1.17.1/update.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/majrusz-library"
    logoFile="logo.jpg"
    credits="Thanks for all your support!"
    authors="Majrusz"
    description='''Library with common code for some of Majrusz's modifications.'''

[[dependencies.majrusz_library]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.majrusz_library]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
